- hosts: test
  gather_facts: yes
  tasks:
  - name: comment the line /etc/chrony.conf
    replace:
      path: /etc/chrony.conf
      regexp: '^server'
      replace: '#server'
      backup: yes
  - name: Add the NTP Server
    blockinfile:
      path: /etc/chrony.conf
      marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      insertafter: "#server 3.centos.pool.ntp.org iburst"
      content: |
        server {{ ntp_hostname }} iburst
  - name: Restart service chronyd, in all cases
    service:
      name: chronyd
      state: restarted
  - name: Verify the Chrony service is active
    shell: systemctl status chronyd.service
    register: result
  - debug:
      var: result.stdout_lines[0],result.stdout_lines[2]
  - name: verify the chrony servers syncing or not
    shell: chronyc sources
    register: result
  - debug:
      var: result.stdout_lines
  - name: Verify the timezone
    shell: timedatectl
    register: result
  - debug:
      var: result.stdout_lines[3]
  - name: verify the time
    shell: date
    register: result
  - debug:
      var: result.stdout_lines
